@baseUrl = http://localhost:8000/api/v1
@contentType = application/json

### Inscription
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
    "name": "Robototo Agriculteur",
    "email": "test11@agril.bj",
    "password": "password",
    "password_confirmation": "password",
    "role": "farmer"
}

### Connexion
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "test11@agril.bj",
    "password": "password"
}

### Profil connecté
GET {{baseUrl}}/auth/me
Authorization: Bearer 8|Vig96ntdeAhypIUiVvz2Nirdga0QY0QW3kSyzHMK43236212

### Déconnexion
POST {{baseUrl}}/auth/logout
Authorization: Bearer 8|Vig96ntdeAhypIUiVvz2Nirdga0QY0QW3kSyzHMK43236212